= Intellj
:stylesheet: ../../style.css

Un IDE est un environnement complet qui permet de travailler plus vite en regroupant de multiples outils de développement dans une même interface.

Intellij est développé par JetBrains  qui maitient tout une suite de logiciels pour divers languages : php, python, ruby...

Intellij existe en 2 versions : communautaire et ultimate.

La version communautaire est suffisante pour faire du java, du groovy ou du scala.

La version ultimate rajoute le web, jee et d'avantages de languages et plateformes (feature list ).

Intellij ultimate n'est pas gratuit mais ses qualités justifient amplement un tarif qui n'est pas très élevé.

Les autres IDEs les plus utilisés sont :

* *Eclipse* : l'IDE le plus utilisé car il est extrêmement complet et gratuit. Ses nombreux plugins font sa richesse.
* *Netbeans* : c'est l'IDE de référence développé par Oracle. Il est gratuit et suit très bien les spécifications jee. Ce n'est pourtant pas l'environnement de choix pour les utilisateurs avancés.

Nous allons intégrer notre projet naissant dans Intellij

== Projets et modules

Un projet est la structure de base. C'est tout ce qu'on voit dans la fenêtre.

Il définit un sdk et un niveau de compatibilité du language java (1.6, 1.7...).

Il contient 1 ou plusieurs modules. Un module contient des fichiers sources.

Chaque module est indépendant et possède ses fichiers et des librairies.

== Préférences

Les préférences sont accessibles via le menu File > Other settings > Default Settings...

Elles sont aussi disponibles via l'icône settings de la barre d'outils ou bien via le raccourcis ⌘ ,

Elles permettent de régler beaucoup des aspects de l'IDE : formattage des sources, environnement java...

La définition des modules est accessible via l'icône modules. On peut y voir les librairies utilisées et la configuration des modules.

== Création du projet



== Import du module gradle

== Mise à jour du build.gradle

== Maintenant

Nous allons maitenant pouvoir ajouter du code