= Java
:stylesheet: ../../style.css
:icons: font

Java est un language objet dont la synthaxe est dérivée du C.

NOTE: ce document ne contient que quelques rappels et n'est pas du tout exhaustif

== compilation et bytecode

Les fichiers .java sont compilés en .class qui contiennent du byte code.

Les fichiers .class peuvent être exécuté partout ou il y a une *Java Virtual Machine* (jvm).

La commande javac de compilation fait partie du *Java Development Kit* (jdk).

== packages, classes et import

Les classes java sont organisées en *packages* (répertoires).

Un `import` permet d'utiliser une autre classe depuis la classe courante.

Au lancement de l'application, toutes les classes présentes dans le classpath sont disponibles à l'import.

== class, interface, enum et annotation

Il existe plusieurs type d'éléments en java.

[source,java]
.class
----
public class Person {

}
----

[source,java]
.interface
----
public interface Runnable {

}
----

[source,java]
.enum
----
public enum Gender {
    MALE, FEMALE;
}
----

[source,java]
.@annotation
----
// déclaration de l'annotation
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface Validate {

}

// peut être utilisé sur d'autres éléments
@Validate
public class MyModel {

}
----

== stacktrace

Lorsqu'une exception est levée (ex: `throw new IllegalArgumentException('name must be not null')`), le flow d'exécution est arrêté et elle remonte vers l'appelant.

Au moment où elle est levée, l'exception capture la pile d'appels. Il est possible d'afficher cette stacktrace, par exemple :

[source,java]
----
java.io.FileNotFoundException: my_file.txt
        at java.io.FileInputStream.<init>(FileInputStream.java)
        at java.io.FileInputStream.<init>(FileInputStream.java)
        at Main.main(Main.java:19)
----

Cela peut sembler un peu compact au départ mais c'est très complet.

== gestion de la mémoire



== l'évolution du language

== Une plateforme riche et diverse