= Le MVC
:stylesheet: ../../style.css

Voici la liste des bugs répertoriés en relation avec le MVC

****
* <<MVC-1>>  : forward vers la jsp contact.jsp
* <<MVC-2>>  : keep tag in input after search in recettes.jsp
* <<MVC-3>>  : SearchForm what about invalid page index ?
* <<MVC-4>>  : Pagination unit test : wrong page count
* <<MVC-5>>  : Pagination unit test : getPages() pages are hardcoded
* <<MVC-6>>  : IndexController : handle not found and create page 404 on unknow recipe
* <<MVC-7>>  : Date Failed to convert property value of type java.lang.String to required type java.util.Date for property date; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.String to type @javax.validation.constraints.NotNull @org.springframework.format.annotation.DateTimeFormat java.util.Date for value 2015-04-02; nested exception is java.lang.IllegalArgumentException: Unable to parse 2015-04-02
* <<MVC-8>>  :
* <<MVC-9>>  : randomColumns() column height are too random ?
* <<MVC-10>> :
****

NOTE: Les modifications dans les controllers nécessitent de redémarrer le serveur `gradle tomcatRun`

NOTE: link:../B-mvc/index.html[l'annexe B] résume les concepts liés au MVC pour le web

== [[MVC-1]]MVC-1 :

== [[MVC-2]]MVC-2 :

== [[MVC-3]]MVC-3 :

[[MVC-4]]

[[MVC-5]]

[[MVC-6]]

[[MVC-7]]

[[MVC-8]]

[[MVC-9]]

[[MVC-10]]
