
include::../../header.adoc[]

= Annexe A : Les Java Server Pages (JSP)

Les JSP sont la technologie de templating

[source,jsp]
----
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
   <head></head>
   <body>
      Hello ${name} !<br>
      Hello <%=name%> !<br>
   </body>
</html>
----

Ils disposent de mécaniques puissantes afin de créer le rendu html pour une page web.

Ils peuvent également générer n'importe quel type de contenu textuel, comme du XML par exemple.

Les jsp sont compilées en servlet java au moment de leur interprétation, avant d'être exécutées.

== Les directives jsp

Les directives contrôlent la manière dont le compilateur doit générer la servlet.

Le format d'une directive est le suivant.

[source,jsp]
<%@ directive { attribut="valeur" } %>

Par exemple afin de contrôler le type mime et l'encoding de la page.

[source,jsp]
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

Ou bien l'inclusion d'un autre fichier.

[source,jsp]
<%@ include file="autre_fichier.jsp" %>

== Les actions jsp

Les actions JSP sont des balises qui appellent des fonctions sur serveur HTTP

Le format d'une action est le suivant.

[source,jsp]
<jsp:action { attribut="valeur" } />

Par exemple, un include s'écrit comme suit.

[source,jsp]
<jsp:include page="autre_fichier.jsp" >
   <jsp:param name="monParam" value="valeur" />
</jsp:include>

En pratique, les actions sont peu utilisées car il existe des mécanismes plus puissants.

== Variables implicites

Les variables implicites sont des variables qui sont présentes dans toutes les jsp.

En voici quelques unes

* out : le JSPWriter utilisé pour envoyer la réponse HTTP au client
* page : la Servlet elle même
* pageContext : les données associées à la page entière
* request : la requête
* response : la réponse
* session : la session
* cookie : les cookies
* header : tous les headers
* param : tous paramètres

Il est rare d'avoir recours à ces variables dans les jsp car dans le cadre du MVC, c'est le rôle du contrôleur.

== Expression language

C'est une notation simple et puissante utilisable partout dans les jsp.

[source,jsp]
${expression}

Elle permet d'aller chercher des valeurs en parcourant tous les scopes (page, request, session et application) et d'effectuer des opérations.

L'expression suivante

[source,jsp]
${cart.items[2].name}

Synthétise un appel qui pourrait être écrit comme suit

[source,jsp]
----
Cart cart = (Cart) request.getSession().getAttribute("cart");

String name = cart.getItems().get(2).getName();

response.getWriter().write(name);
----

== Custom tags et fonctions

Un custom tag est un nouvel élément du language que l'on peut soi même définir.

Afin de pouvoir l'utiliser, il suffit d'utiliser la directive taglib suivante.

[source,jsp]
<%@ taglib uri="/WEB-INF/tld/mataglib.tld" prefix="mataglib" %>

Une taglib peut contenir des tags et des fonctions.

Les tags, selon le besoin, peuvent être implémentés par des classes java ou bien des fichiers tag.

Voici un exemple d'appel à un tag.

[source,jsp]
<mataglib:faituntruc att1="valeur1" att2="valeur2" >

Et une fonction.

[source,jsp]
${mataglib:faitca("valeur1")}

La définition des customs tags et fonctions se fait via un fichier tld que l'on place dans `WEB-INF/tld`

[source,xml]
.util.tld
----
<?xml version="1.0" encoding="UTF-8" ?>
<taglib xmlns="http://java.sun.com/xml/ns/j2ee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee
	web-jsptaglibrary_2_0.xsd" version="2.0">

    <tlibversion>1.0</tlibversion>
	  <jspversion>2.0</jspversion>
    <shortname>pagination</shortname>
    <uri>http://com.acme.tags/pagination</uri>
    <info>Pagination taglib</info>

    <tag>
        <!-- nom du tag -->
        <name>pagination</name>
        <!-- classe java contenant le code du tag -->
        <tagclass>com.acme.tag.PaginationTag</tagclass>
        <body-content>empty</body-content>
        <info>Helper tag that builds a Pagination object used to build paginations menus.</info>
        <!-- liste des attributs supportés -->
        <attribute>
            <name>var</name>
            <required>false</required>
            <rtexprvalue>true</rtexprvalue>
        </attribute>
        <attribute>
            <name>menuSize</name>
            <required>false</required>
            <rtexprvalue>true</rtexprvalue>
        </attribute>
        <attribute>
            <name>pageIndex</name>
            <required>false</required>
            <rtexprvalue>true</rtexprvalue>
        </attribute>
        <attribute>
            <name>pageSize</name>
            <required>false</required>
            <rtexprvalue>true</rtexprvalue>
        </attribute>
        <attribute>
            <name>count</name>
            <required>false</required>
            <rtexprvalue>true</rtexprvalue>
        </attribute>
        <attribute>
            <name>pageQuery</name>
            <required>false</required>
            <rtexprvalue>true</rtexprvalue>
        </attribute>
        <attribute>
            <name>pageResult</name>
            <required>false</required>
            <rtexprvalue>true</rtexprvalue>
        </attribute>
    </tag>

    <function>
        <!-- nom de la fonction -->
        <name>slug</name>
        <!-- classe java contenant le code de la fonction -->
        <function-class>com.acme.FormatUtils</function-class>
        <!-- signature de la méthode *statique* dans la classe java -->
        <function-signature>java.lang.String slug(java.lang.String)</function-signature>
    </function>
</taglib>
----

Il est possible de packager ces éléments dans une librairie afin de les réutiliser dans différents projets.

== Tag files

Un tag file (.tag) est un morceau de jsp réutilisable en tant que custom tag.

Voici un exemple de tag file

[source,html]
.hello.tag
----
<%@ tag body-content="empty" pageEncoding="UTF-8" %>

<%@ attribute name="name" required="true" %> <1>

<h2><font color="black">hello ${name}!</font></h2> <2>
----
<1> paramètre name obligatoire
<2> synthaxe jsp classique

Les fichiers tag sont placé dans /WEB-INF/tags/.

Afin de pouvoir utiliser un ensemble de fichiers tag, il faut utiliser la directive taglib :

[source,html]
----
<%@ taglib prefix="fragments" tagdir="/WEB-INF/tags/fragments" %>
----

== Jstl

La java standard tag library est la librairie de tag la plus utilisée.

Elle contient 4 taglibs et un ensemble de fonctions:

* <c:/> : la taglib essentielle avec le contrôle de flot

[source,html]
<c:if test="${empty param['name']}">Nom inconnu</c:if>

* <fmt:/> : le fomattage

[source,html]
<fmt:formatDate value="${date}" pattern="dd/MM/yyyy"/c:if>

* <sql:/> : l'accès aux bases de données
* <x:/> : le parsing xml
* ${fn:} : la manipulation de chaînes de charactères

[source,html]
----
${fn:escapeXml("les <balises> xml & html")} <1>
----
<1> produit `"les \&lt;balises\&gt; xml \&amp; html"`
