= Annexe A : Les Java Server Pages (JSP)
:stylesheet: ../../style.css

Les JSP sont la technologie de templating

[source,jsp]
----
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
   <head></head>
   <body>
      Hello ${name} !<br>
      Hello <%=name%> !<br>
   </body>
</html>
----

Ils disposent de mécaniques puissantes afin de créer le rendu html pour une page web.

Ils peuvent également générer n'importe quel type de contenu textuel, comme du XML par exemple.

Les jsp sont compilées en servlet java au moment de leur interprétation, avant d'être exécutées.

== Les directives jsp

Les directives contrôlent la manière dont le compilateur doit générer la servlet.

Le format d'une directive est le suivant.

[source,jsp]
<%@ directive { attribut="valeur" } %>

Par exemple afin de contrôler le type mime et l'encoding de la page.

[source,jsp]
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

Ou bien l'inclusion d'un autre fichier.

[source,jsp]
<%@ include file="autre_fichier.jsp" %>

== Les actions jsp

Les actions JSP sont des balises qui appellent des fonctions sur serveur HTTP

Le format d'une action est le suivant.

[source,jsp]
<jsp:action { attribut="valeur" } />

Par exemple, un include s'écrit comme suit.

[source,jsp]
<jsp:include page="autre_fichier.jsp" >
   <jsp:param name="monParam" value="valeur" />
</jsp:include>

En pratique, les actions sont peu utilisées car il existe des mécanismes plus puissants.

== Variables implicites

Les variables implicites sont des variables qui sont présentes dans toutes les jsp.

En voici quelques unes

* out : le JSPWriter utilisé pour envoyer la réponse HTTP au client
* page : la Servlet elle même
* pageContext : les données associées à la page entière
* request : la requête
* response : la réponse
* session : la session
* cookie : les cookies
* header : tous les headers
* param : tous paramètres

Il est rare d'avoir recours à ces variables dans les jsp car dans le cadre du MVC, c'est le rôle du contrôleur.

== Expression language

C'est une notation simple et puissante utilisable partout dans les jsp.

[source,jsp]
${expression}

Elle permet d'aller chercher des valeurs en parcourant tous les scopes (page, request, session et application) et d'effectuer des opérations.

L'expression suivante

[source,jsp]
${cart.items[2].name}

Synthétise un appel qui pourrait être écrit comme suit

[source,jsp]
----
Cart cart = (Cart) request.getSession().getAttribute("cart");

String name = cart.getItems().get(2).getName();

response.getWriter().write(name);
----

== Custom tags et fonctions

Un custom tag est un nouvel élément du language que l'on peut soi même définir.

Afin de pouvoir l'utiliser, il suffit d'utiliser la directive taglib suivante.

[source,jsp]
<%@ taglib uri="/WEB-INF/tld/mataglib.tld" prefix="mataglib" %>

Une taglib peut contenir des tags et des fonctions.

Les tags, selon le besoin, peuvent être implémentés par des classes java ou bien des fichiers tag.

Voici un exemple d'appel à un tag.

[source,jsp]
<mataglib:faituntruc att1="valeur1" att2="valeur2" >

Et une fonction.

[source,jsp]
${mataglib:faitca("valeur1")}

== Tag files

== Jstl

La java standard tag library est la librairie de tag la plus utilisée.

Elle contient 4 taglibs et un ensemble de fonctions:

* <c:/> : la taglib essentielle avec le contrôle de flot

[source,jsp]
<c:if test="${empty param['name']}">Nom inconnu</c:if>

* <fmt:/> : le fomattage

[source,jsp]
<fmt:formatDate value="${date}" pattern="dd/MM/yyyy"/c:if>

* <sql:/> : l'accès aux bases de données
* <x:/> : le parsing xml
* ${fn:} : la manipulation de chaînes de charactères

[source,jsp]
${fn:escapeXml("les <balises> xml & html")} <%-- "les &lt;balises&gt; xml &amp; html" --%>